resources:
  - argocd-install.yaml
  - argocd-route.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-redis
    path: patch-argocd-redis-securitycontext.yaml

  - path: patch-argocd-cmd-params.yaml
